import React, { useState, useEffect } from 'react';
import { MapPin, Calendar, Activity } from 'lucide-react';

const Dashboard = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  // Fetch the JSON generated by Python
  useEffect(() => {
    fetch('/satellite_data.json')
      .then(res => res.json())
      .then(d => {
        setData(d);
        setLoading(false);
      });
  }, []);

  if (loading) return <div className="flex h-screen items-center justify-center bg-gray-50 text-gray-400">Loading Satellite Link...</div>;

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans p-8">
      {/* Header */}
      <header className="mb-12 flex justify-between items-center max-w-6xl mx-auto">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">Orbital View</h1>
          <p className="text-slate-500 mt-1 flex items-center gap-2">
            <Activity size={16} className="text-green-500" />
            System Online • Last Sync: {data.last_updated}
          </p>
        </div>
        <div className="bg-white px-4 py-2 rounded-lg shadow-sm border border-gray-200">
           <span className="text-sm font-semibold text-slate-600">NASA GIBS Feed</span>
        </div>
      </header>

      {/* Grid of Locations */}
      <main className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {data.locations.map((loc) => (
          <div key={loc.id} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow border border-gray-100 group">
            
            {/* The Satellite Image */}
            <div className="relative h-64 overflow-hidden bg-gray-100">
              <img 
                src={loc.image_url} 
                alt={loc.name} 
                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
              />
              <div className="absolute top-4 right-4 bg-black/50 backdrop-blur-md text-white text-xs px-3 py-1 rounded-full border border-white/10">
                Live Feed
              </div>
            </div>

            {/* Card Content */}
            <div className="p-6">
              <h2 className="text-xl font-bold text-slate-900 mb-2">{loc.name}</h2>
              
              <div className="flex items-center gap-4 text-sm text-slate-500 mb-4">
                <div className="flex items-center gap-1">
                  <MapPin size={14} />
                  {loc.coordinates}
                </div>
                <div className="flex items-center gap-1">
                  <Calendar size={14} />
                  {data.last_updated}
                </div>
              </div>

              <button className="w-full py-2.5 bg-slate-900 hover:bg-slate-800 text-white text-sm font-medium rounded-lg transition-colors">
                Analyze Sector
              </button>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
};

export default Dashboard;

